name: Build Windows

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Setup
        uses: compnerd/gha-setup-swift@v0.3.0
        with:
          branch: swift-6.0-release
          tag: 6.0-RELEASE

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build product swift-bundler
        run: swift build --product swift-bundler
